"""empty message

Revision ID: 052924a8a8d4
Revises: 6391f08492ed
Create Date: 2021-11-01 18:04:01.686729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '052924a8a8d4'
down_revision = '6391f08492ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_info_ibfk_1', 'book_info', type_='foreignkey')
    op.create_foreign_key(None, 'book_info', 'category_list', ['category_id'], ['id'])
    op.drop_column('book_info', 'Nomenclature_id')
    op.drop_constraint('picture_ibfk_1', 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'book_info', ['isbn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key('picture_ibfk_1', 'picture', 'category_list', ['isbn_id'], ['id'])
    op.add_column('book_info', sa.Column('Nomenclature_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book_info', type_='foreignkey')
    op.create_foreign_key('book_info_ibfk_1', 'book_info', 'category_list', ['Nomenclature_id'], ['id'])
    op.drop_column('book_info', 'category_id')
    # ### end Alembic commands ###
