"""empty message

Revision ID: 3d7535a5f9c3
Revises: 052924a8a8d4
Create Date: 2021-11-01 18:40:11.952786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7535a5f9c3'
down_revision = '052924a8a8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('platform_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_info', 'platform_id')
    # ### end Alembic commands ###
