"""empty message

Revision ID: 528430e0aaf9
Revises: e65d0484ce36
Create Date: 2021-11-03 11:20:04.747382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '528430e0aaf9'
down_revision = 'e65d0484ce36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('show_priority', sa.Integer(), nullable=False))
    op.add_column('book_info', sa.Column('platform', sa.Integer(), nullable=False))
    op.add_column('book_info', sa.Column('platform_product_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_info_ibfk_5', 'book_info', type_='foreignkey')
    op.create_foreign_key(None, 'book_info', 'platform', ['platform'], ['id'])
    op.drop_column('book_info', 'platform_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book_info', type_='foreignkey')
    op.create_foreign_key('book_info_ibfk_5', 'book_info', 'platform', ['platform_id'], ['id'])
    op.drop_column('book_info', 'platform_product_id')
    op.drop_column('book_info', 'platform')
    op.drop_column('book_info', 'show_priority')
    # ### end Alembic commands ###
