"""empty message

Revision ID: 8b5da17bb4ae
Revises: c8745345e5c1
Create Date: 2021-11-01 17:44:39.467512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b5da17bb4ae'
down_revision = 'c8745345e5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_info', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('isbn', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
