"""empty message

Revision ID: 8bbf4cce0489
Revises: f5cd64156df2
Create Date: 2021-11-03 13:16:48.043507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbf4cce0489'
down_revision = 'f5cd64156df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_info_isbn'), 'book_info', ['isbn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_info_isbn'), table_name='book_info')
    # ### end Alembic commands ###
