"""empty message

Revision ID: 94ce27467765
Revises: 983a60b66b95
Create Date: 2021-11-01 21:26:33.766997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94ce27467765'
down_revision = '983a60b66b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_info', 'e_book_url')
    op.drop_column('book_info', 'cover_photo')
    op.drop_column('book_info', 'product_url')
    op.drop_column('book_info', 'page')
    op.drop_column('book_info', 'size')
    op.drop_column('book_info', 'description')
    op.drop_column('book_info', 'title')
    op.drop_column('book_info', 'table_of_content')
    op.drop_column('book_info', 'publish_date')
    op.drop_column('book_info', 'author_intro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('author_intro', mysql.TEXT(), nullable=True))
    op.add_column('book_info', sa.Column('publish_date', mysql.DATETIME(), nullable=True))
    op.add_column('book_info', sa.Column('table_of_content', mysql.TEXT(), nullable=True))
    op.add_column('book_info', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('book_info', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('book_info', sa.Column('size', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('book_info', sa.Column('page', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book_info', sa.Column('product_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('book_info', sa.Column('cover_photo', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('book_info', sa.Column('e_book_url', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
