"""empty message

Revision ID: 983a60b66b95
Revises: 
Create Date: 2021-11-01 21:21:38.640038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a60b66b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('size', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'book_info', 'publisher', ['publisher'], ['id'])
    op.create_foreign_key(None, 'book_info', 'category_list', ['category_id'], ['id'])
    op.create_foreign_key(None, 'book_info', 'author', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_info', type_='foreignkey')
    op.drop_constraint(None, 'book_info', type_='foreignkey')
    op.drop_constraint(None, 'book_info', type_='foreignkey')
    op.drop_column('book_info', 'size')
    # ### end Alembic commands ###
