"""empty message

Revision ID: e65d0484ce36
Revises: 94ce27467765
Create Date: 2021-11-01 21:28:31.293082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65d0484ce36'
down_revision = '94ce27467765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_info', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('book_info', sa.Column('size', sa.String(length=30), nullable=True))
    op.add_column('book_info', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.add_column('book_info', sa.Column('table_of_content', sa.Text(), nullable=True))
    op.add_column('book_info', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('book_info', sa.Column('author_intro', sa.Text(), nullable=True))
    op.add_column('book_info', sa.Column('cover_photo', sa.String(length=255), nullable=True))
    op.add_column('book_info', sa.Column('page', sa.Integer(), nullable=True))
    op.add_column('book_info', sa.Column('product_url', sa.String(length=255), nullable=True))
    op.add_column('book_info', sa.Column('e_book_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_info', 'e_book_url')
    op.drop_column('book_info', 'product_url')
    op.drop_column('book_info', 'page')
    op.drop_column('book_info', 'cover_photo')
    op.drop_column('book_info', 'author_intro')
    op.drop_column('book_info', 'description')
    op.drop_column('book_info', 'table_of_content')
    op.drop_column('book_info', 'publish_date')
    op.drop_column('book_info', 'size')
    op.drop_column('book_info', 'title')
    # ### end Alembic commands ###
